---
- name: Instalacao do puppet server para o RedHat
  yum:
    name:  puppetserver
    state: present
  when: ansible_os_family == "RedHat"
  notify:
  - Reinicia o server
 
- name: Instalacao do puppet server para o Debian
  apt:
    name: puppetserver
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"  
  notify:
  - Reinicia o server
