---
- name: Instalacao do client do puppet
  yum:
    name:  puppet-agent
    state: present
  when: ansible_os_family == "RedHat"
  notify:
  - Reinicia o agente
 
- name: Instala o repo para o Debian 
  apt:
    name: puppet-agent
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"  
  notify:
  - Reinicia o agente
