---
- name: Instalacao do client do puppet
  yum:
    name:  puppetserver
    state: present
  when: ansible_os_family == "RedHat"
 
- name: Instala o repo para o Debian 
  apt:
    name: puppetserver
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"  
